# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fed64ae7285a3d03560c03fdf4384fea3c1b65180faae9b25ce36414f889ade861232a756e9983ffecbd084928126d4882ac9682e954a3c3a1868d7506a1c7d

test:
  secret_key_base: e9246fbd33ba659c89ecbebbfa42d57bb674a837ee27a50bc092db17a97e3bab9e38f2e8a64aa9b07debc375bbb3b67ede666144489d158fa6e82cc27077534f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
